### ISSUE TITLE
How can I use this without passing constraints?

### ISSUE THREAD

**Issue by hagile** [hsusmita/GrowingTextViewHandler-objc#3]
Hi there, first of all, thank you so much this awesome thing. I found it easy to use and setup (if you're using AutoLayout & StoryBoard). However, in my app, I'm not having a storyboard (or XIBs ) and AutoLayout at all. However to use this handler, I need to pass constraints. How can I use without passing it?

In this method, `- (id)initWithTextView:(UITextView *)textView
  withHeightConstraint:(NSLayoutConstraint *)heightConstraint`, if I pass nil for `heightConstraint` then it'll stop growing.

Is it possible, even if not, then just give me an idea so that I can achieve this on my self.

Thanks!

**Comment by hagile** [comment]
In this method, `- (id)initWithTextView:(UITextView *)textView
  withHeightConstraint:(NSLayoutConstraint *)heightConstraint`, if I pass nil for `heightConstraint` then it'll stop growing.

**Comment by susmita-fueled** [comment]
@hagile This library is meant to take advantage of auto-feature. When a user types, new height is calculated and the height constraint  id updated accordingly. So it will not work if you will not provide the height constraint. However if you want to extend feature for non-autolayout cases, you can tweak the method - (void)resizeTextViewWithAnimation:(BOOL)animated. Here "verticalAlignmentConstant" is calculated. At this point you can set the frame of the textView.

I would strongly recommend that you should be using auto-layout.

**Comment by hsusmita** [comment]
@hagile This library is meant to take advantage of auto-feature. When a user types, new height is calculated and the height constraint id updated accordingly. So it will not work if you will not provide the height constraint. However if you want to extend feature for non-autolayout cases, you can tweak the method - (void)resizeTextViewWithAnimation:(BOOL)animated. Here "verticalAlignmentConstant" is calculated. At this point you can set the frame of the textView.

I would strongly recommend that you should be using auto-layout.

**Comment by hagile** [comment]
@hsusmita, agreed that I should move on for AL, but unfortunately, I'm at something from where I can't change it right now. I'll definitely using it for my next project. However, thank for your quick response and tip. I'll dig into it and will let you know. Thanks again :)

**Comment by hsusmita** [comment]
@hagile I have pushed the implementation on the branch "frameResize". You can fine tune it according to you need.

**Comment by hagile** [comment]
@hsusmita, I'm not able find "frameResize" ? Where it is?

**Comment by hsusmita** [comment]
Checkout the branch "frameResize"

**Comment by hagile** [comment]
@hsusmita, thank you so much, that was a great help :+1:
